# Generated by Django 4.2.7 on 2023-11-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctorname", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("experience", models.PositiveIntegerField(blank=True, null=True)),
                ("positive_count", models.PositiveIntegerField(blank=True, null=True)),
                ("negative_count", models.PositiveIntegerField(blank=True, null=True)),
                ("neutral_count", models.PositiveIntegerField(blank=True, null=True)),
                ("total_reviews", models.PositiveIntegerField(blank=True, null=True)),
                ("rank_math", models.FloatField(blank=True, null=True)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
