# Generated by Django 4.2.7 on 2023-11-12 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="doctor_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="chatbot.doctordetails",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
