# Generated by Django 4.2.7 on 2023-11-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_review_doctor_id_review_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctordetails",
            name="contact_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="doctordetails",
            name="hospital_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="doctordetails",
            name="place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
