# Generated by Django 4.2.7 on 2023-12-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_multipledetails_singledoctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultipleDetails',
            new_name='MultipleDoctors',
        ),
    ]
