# Generated by Django 5.0.2 on 2024-02-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_delete_singledoctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multipledoctors",
            name="department",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="multipledoctors",
            name="user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
